# Generated by Django 4.0.6 on 2022-09-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='apropos',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
