# Generated by Django 4.0.6 on 2022-10-14 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syndicat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='la_clinique',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clinique', to='syndicat.clinique'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='le_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='syndicat.service'),
        ),
    ]
