# Generated by Django 4.0.6 on 2022-08-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='contenu',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='extrait',
            field=models.TextField(null=True),
        ),
    ]
