# Generated by Django 4.0.6 on 2023-03-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='photo',
            field=models.ImageField(default='', upload_to='img-produits/'),
        ),
    ]
