# Generated by Django 4.0.6 on 2023-02-01 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syndicat', '0002_alter_personnel_la_clinique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='commanditaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commanditaire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produit',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
