# Generated by Django 4.0.6 on 2023-05-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicat', '0002_rename_user_name_utilisateur_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='start_date',
            new_name='date_joined',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
