# Generated by Django 4.0.6 on 2023-02-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicat', '0003_alter_commande_commanditaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='disponible',
            field=models.BooleanField(),
        ),
    ]
