# Generated by Django 4.0.6 on 2023-05-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicat', '0003_rename_start_date_utilisateur_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='civilite',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='civilite',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
