# Generated by Django 4.0.6 on 2023-02-27 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syndicat', '0004_alter_produit_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='syndicat.produit'),
        ),
    ]
